name: 'Cleanup Release on Failure'
description: 'Atomic cleanup - removes pushed Docker images and charts on release failure'

inputs:
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  registry-org:
    description: 'Registry organization/namespace'
    required: true
  tag:
    description: 'Release tag to clean up'
    required: true
  helm-registry:
    description: 'OCI registry URL for Helm charts'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true
  services:
    description: 'Pipe-separated list of services to clean up (e.g., "service1|service2")'
    required: false
  charts:
    description: 'Pipe-separated list of charts to clean up (e.g., "chart1|chart2")'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Extract repository owner
      id: repo-info
      run: |
        REPO_OWNER="${GITHUB_REPOSITORY%%/*}"
        echo "owner=$REPO_OWNER" >> $GITHUB_OUTPUT
        echo "Repository owner: $REPO_OWNER"
      shell: bash

    - name: Cleanup Docker images
      if: inputs.services != ''
      run: |
        REGISTRY="${{ inputs.registry }}"
        REGISTRY_ORG="${{ inputs.registry-org }}"
        TAG="${{ inputs.tag }}"
        GITHUB_TOKEN="${{ inputs.github-token }}"
        SERVICES="${{ inputs.services }}"
        REPO_OWNER="${{ steps.repo-info.outputs.owner }}"
        
        echo "Cleaning up Docker images..."
        OLD_IFS="$IFS"
        IFS='|' read -ra SERVICE_ARRAY <<< "$SERVICES"
        
        for service in "${SERVICE_ARRAY[@]}"; do
          if [ -n "$service" ]; then
            IMAGE="$REGISTRY/$REGISTRY_ORG/$service:$TAG"
            echo "  Attempting to delete package: $service (tag: $TAG)"
            
            # Get package versions using GitHub API
            API_RESPONSE=$(curl -s \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/orgs/$REPO_OWNER/packages/container/$service/versions" 2>/dev/null || echo "[]")
            
            if [ "$API_RESPONSE" != "[]" ] && [ -n "$API_RESPONSE" ]; then
              # Extract version IDs
              PACKAGE_VERSIONS=$(echo "$API_RESPONSE" | \
                grep -o "\"id\":[0-9]*" | \
                cut -d: -f2 || echo "")
              
              if [ -n "$PACKAGE_VERSIONS" ]; then
                for version_id in $PACKAGE_VERSIONS; do
                  # Check if this version has the tag we're looking for
                  VERSION_INFO=$(curl -s \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github+json" \
                    "https://api.github.com/orgs/$REPO_OWNER/packages/container/$service/versions/$version_id" 2>/dev/null || echo "{}")
                  
                  if echo "$VERSION_INFO" | grep -q "\"$TAG\""; then
                    echo "    Deleting package version ID: $version_id (tag: $TAG)"
                    DELETE_RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null \
                      -X DELETE \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      "https://api.github.com/orgs/$REPO_OWNER/packages/container/$service/versions/$version_id")
                    
                    if [ "$DELETE_RESPONSE" = "204" ]; then
                      echo "    ✅ Successfully deleted version $version_id"
                    else
                      echo "    ⚠️  Failed to delete version $version_id (HTTP $DELETE_RESPONSE)"
                    fi
                  fi
                done
              else
                echo "    ⚠️  No package versions found for service $service"
              fi
            else
              echo "    ⚠️  Could not fetch package versions (API error or no versions)"
            fi
            
            echo "    Image cleanup attempted: $IMAGE"
          fi
        done
        IFS="$OLD_IFS"
      shell: bash

    - name: Cleanup Helm charts
      if: inputs.charts != ''
      run: |
        HELM_REGISTRY="${{ inputs.helm-registry }}"
        TAG="${{ inputs.tag }}"
        CHARTS="${{ inputs.charts }}"
        
        echo "Cleaning up Helm charts..."
        echo "⚠️  Note: OCI registry chart deletion via API is limited"
        echo "⚠️  Charts may need manual deletion from registry"
        
        OLD_IFS="$IFS"
        IFS='|' read -ra CHART_ARRAY <<< "$CHARTS"
        
        for chart in "${CHART_ARRAY[@]}"; do
          if [ -n "$chart" ]; then
            CHART_REF="$HELM_REGISTRY/$chart:$TAG"
            echo "  Chart marked for cleanup: $CHART_REF"
            echo "    Note: Manual deletion may be required from GitHub Packages"
          fi
        done
        IFS="$OLD_IFS"
      shell: bash

    - name: Cleanup summary
      run: |
        REGISTRY="${{ inputs.registry }}"
        REGISTRY_ORG="${{ inputs.registry-org }}"
        TAG="${{ inputs.tag }}"
        HELM_REGISTRY="${{ inputs.helm-registry }}"
        SERVICES="${{ inputs.services }}"
        CHARTS="${{ inputs.charts }}"
        
        echo ""
        echo "=== Cleanup Summary ==="
        if [ -n "$SERVICES" ]; then
          echo ""
          echo "Docker Images cleanup attempted:"
          OLD_IFS="$IFS"
          IFS='|' read -ra SERVICE_ARRAY <<< "$SERVICES"
          for service in "${SERVICE_ARRAY[@]}"; do
            [ -n "$service" ] && echo "  - $REGISTRY/$REGISTRY_ORG/$service:$TAG"
          done
          IFS="$OLD_IFS"
        fi
        if [ -n "$CHARTS" ]; then
          echo ""
          echo "Helm Charts (may require manual cleanup):"
          OLD_IFS="$IFS"
          IFS='|' read -ra CHART_ARRAY <<< "$CHARTS"
          for chart in "${CHART_ARRAY[@]}"; do
            [ -n "$chart" ] && echo "  - $HELM_REGISTRY/$chart:$TAG"
          done
          IFS="$OLD_IFS"
        fi
        echo ""
        echo "⚠️  Please verify cleanup was successful in GitHub Packages"
        echo "⚠️  If cleanup failed, manually delete the packages listed above"
      shell: bash

