apiVersion: v2
name: observability-dataprepper
description: A Helm chart to add Tracing functionality for the Agent Management Platform, by Deploying and Configuring Data Prepper and the Traces Observer Service.
type: application
version: 0.0.12
appVersion: "amp/v0.0.12"
