name: 'Build and Push Docker Image'
description: 'Build and push a Docker image to GitHub Container Registry'

inputs:
  service:
    description: 'Service name (directory name containing Dockerfile)'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  registry-org:
    description: 'Registry organization/namespace'
    required: true
  tag:
    description: 'Image tag (usually release tag)'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.service }}
        file: ./${{ inputs.service }}/Dockerfile
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.registry-org }}/${{ inputs.service }}:${{ inputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      shell: bash

    - name: Log image details
      run: |
        echo "Built and pushed: ${{ inputs.registry }}/${{ inputs.registry-org }}/${{ inputs.service }}:${{ inputs.tag }}"
      shell: bash

