apiVersion: v2
name: wso2-amp-observability-extension
description: A Helm chart to add Tracing functionality for the Agent Management Platform, by Deploying and Configuring Data Prepper and the Traces Observer Service.
type: application
version: 0.1.12
appVersion: "amp/v0.1.12"

keywords:
  - wso2
  - ai
  - agent-management
  - ai-agents
  - observability

maintainers:
  - name: WSO2
    url: https://wso2.com
