name: 'Build and Push Images and Charts'
description: 'Build and push Docker images and Helm charts for a release'

inputs:
  release-tag:
    description: 'Release tag (e.g., v1.0.0)'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  registry-org:
    description: 'Registry organization/namespace'
    required: true
  helm-registry:
    description: 'OCI registry URL for Helm charts'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract release tag and version
      id: version
      run: |
        bash .github/scripts/extract-version.sh "${{ inputs.release-tag }}"
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push agent-manager-service
      id: build-agent-manager
      uses: ./.github/actions/build-docker-image
      with:
        service: agent-manager-service
        registry: ${{ inputs.registry }}
        registry-org: ${{ inputs.registry-org }}
        tag: ${{ inputs.release-tag }}
        github-token: ${{ inputs.github-token }}

    # - name: Build and push console
    #   id: build-console
    #   uses: ./.github/actions/build-docker-image
    #   with:
    #     service: console
    #     registry: ${{ inputs.registry }}
    #     registry-org: ${{ inputs.registry-org }}
    #     tag: ${{ inputs.release-tag }}
    #     github-token: ${{ inputs.github-token }}

    - name: Build and push traces-observer-service
      id: build-traces-observer
      uses: ./.github/actions/build-docker-image
      with:
        service: traces-observer-service
        registry: ${{ inputs.registry }}
        registry-org: ${{ inputs.registry-org }}
        tag: ${{ inputs.release-tag }}
        github-token: ${{ inputs.github-token }}

    - name: Track pushed images
      id: track-images
      run: |
        SERVICES="agent-manager-service|console|traces-observer-service"
        echo "services=$SERVICES" >> $GITHUB_OUTPUT
        echo "Pushed images tracked: $SERVICES"
      shell: bash

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'

    - name: Install yq
      uses: mikefarah/yq@v4
      with:
        version: v4.40.5

    - name: Push agent-management-platform chart
      id: chart-amp
      run: |
        CHART_NAME="agent-management-platform"
        CHART_DIR="./deployment/helm-charts/agent-management-platform"
        
        # Log in to registry
        ACTOR="${GITHUB_ACTOR:-github-actions}"
        echo "${{ inputs.github-token }}" | helm registry login -u "$ACTOR" --password-stdin "${{ inputs.registry }}"
        
        # Package and push
        helm package "$CHART_DIR" --version "${{ steps.version.outputs.version }}"
        helm push "${CHART_NAME}-${{ steps.version.outputs.version }}.tgz" "${{ inputs.helm-registry }}/${CHART_NAME}"
        echo "chart=agent-management-platform" >> $GITHUB_OUTPUT
        echo "✅ Pushed agent-management-platform chart version ${{ steps.version.outputs.version }}"
      shell: bash

    - name: Push build-ci chart
      id: chart-build-ci
      run: |
        CHART_NAME="build-ci"
        CHART_DIR="./deployment/helm-charts/build-ci"
        
        # Log in to registry
        ACTOR="${GITHUB_ACTOR:-github-actions}"
        echo "${{ inputs.github-token }}" | helm registry login -u "$ACTOR" --password-stdin "${{ inputs.registry }}"
        
        # Package and push
        helm package "$CHART_DIR" --version "${{ steps.version.outputs.version }}"
        helm push "${CHART_NAME}-${{ steps.version.outputs.version }}.tgz" "${{ inputs.helm-registry }}/${CHART_NAME}"
        echo "chart=build-ci" >> $GITHUB_OUTPUT
        echo "✅ Pushed build-ci chart version ${{ steps.version.outputs.version }}"
      shell: bash

    - name: Push observability-dataprepper chart
      id: chart-observability
      run: |
        CHART_NAME="observability-dataprepper"
        CHART_DIR="./deployment/helm-charts/observability-dataprepper"
        
        # Log in to registry
        ACTOR="${GITHUB_ACTOR:-github-actions}"
        echo "${{ inputs.github-token }}" | helm registry login -u "$ACTOR" --password-stdin "${{ inputs.registry }}"
        
        # Package and push
        helm package "$CHART_DIR" --version "${{ steps.version.outputs.version }}"
        helm push "${CHART_NAME}-${{ steps.version.outputs.version }}.tgz" "${{ inputs.helm-registry }}/${CHART_NAME}"
        echo "chart=observability-dataprepper" >> $GITHUB_OUTPUT
        echo "✅ Pushed observability-dataprepper chart version ${{ steps.version.outputs.version }}"
      shell: bash

    - name: Track pushed charts
      id: track-charts
      run: |
        CHARTS="agent-management-platform|build-ci|observability-dataprepper"
        echo "charts=$CHARTS" >> $GITHUB_OUTPUT
        echo "Pushed charts tracked: $CHARTS"
      shell: bash

    - name: Mark build and push as successful
      if: success()
      run: |
        echo "✅ Build and push completed successfully"
        echo "All images and charts pushed successfully"
      shell: bash

